//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNSegurosMAUI.Resources.Text {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BNSegurosMAUI.Resources.Text.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACEPTAR.
        /// </summary>
        internal static string Alert_AcceptButtonText {
            get {
                return ResourceManager.GetString("Alert_AcceptButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACEPTAR.
        /// </summary>
        internal static string AlertAcceptButton {
            get {
                return ResourceManager.GetString("AlertAcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCELAR.
        /// </summary>
        internal static string AlertCancelButton {
            get {
                return ResourceManager.GetString("AlertCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error inesperado. Por favor, intente de nuevo..
        /// </summary>
        internal static string AlertDefaultError {
            get {
                return ResourceManager.GetString("AlertDefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta.
        /// </summary>
        internal static string AlertDefaultTitle {
            get {
                return ResourceManager.GetString("AlertDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string AlertErrorTitle {
            get {
                return ResourceManager.GetString("AlertErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El dispositivo no se encuentra conectado a Internet..
        /// </summary>
        internal static string AlertNoConnectivity {
            get {
                return ResourceManager.GetString("AlertNoConnectivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de conexión.
        /// </summary>
        internal static string AlertNoConnectivityTitle {
            get {
                return ResourceManager.GetString("AlertNoConnectivityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay pasos que mostrar en este Siniestro..
        /// </summary>
        internal static string AlertSinisterStepsNoInfo {
            get {
                return ResourceManager.GetString("AlertSinisterStepsNoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CERRAR.
        /// </summary>
        internal static string ClosePageButton {
            get {
                return ResourceManager.GetString("ClosePageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        internal static string Contact_AddressLabel {
            get {
                return ResourceManager.GetString("Contact_AddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono asistente: .
        /// </summary>
        internal static string Contact_AssistantNumberLabel {
            get {
                return ResourceManager.GetString("Contact_AssistantNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN Corredora.
        /// </summary>
        internal static string Contact_BNInsuranceLabel {
            get {
                return ResourceManager.GetString("Contact_BNInsuranceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Lo sentimos! Llamada telefónica fallida..
        /// </summary>
        internal static string Contact_CallErrorMessage {
            get {
                return ResourceManager.GetString("Contact_CallErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Lo sentimos! El número teléfonico no es valido..
        /// </summary>
        internal static string Contact_CallInvalidErrorMessage {
            get {
                return ResourceManager.GetString("Contact_CallInvalidErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud de llamada fallida.
        /// </summary>
        internal static string Contact_CallInvalidErrorTitle {
            get {
                return ResourceManager.GetString("Contact_CallInvalidErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llamada.
        /// </summary>
        internal static string Contact_CallLabel {
            get {
                return ResourceManager.GetString("Contact_CallLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Lo sentimos! Número telefónico no compatible..
        /// </summary>
        internal static string Contact_CallSupportPhoneErrorMessage {
            get {
                return ResourceManager.GetString("Contact_CallSupportPhoneErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indenmización.
        /// </summary>
        internal static string Contact_CompesationLabel {
            get {
                return ResourceManager.GetString("Contact_CompesationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraloría.
        /// </summary>
        internal static string Contact_ComptrollerLabel {
            get {
                return ResourceManager.GetString("Contact_ComptrollerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contáctenos.
        /// </summary>
        internal static string Contact_ContactLabel {
            get {
                return ResourceManager.GetString("Contact_ContactLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio al cliente.
        /// </summary>
        internal static string Contact_CustomerServiceLabel {
            get {
                return ResourceManager.GetString("Contact_CustomerServiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asistencia.
        /// </summary>
        internal static string Contact_InsuranceAsistanceLabel {
            get {
                return ResourceManager.GetString("Contact_InsuranceAsistanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corredores.
        /// </summary>
        internal static string Contact_InsurancesLabel {
            get {
                return ResourceManager.GetString("Contact_InsurancesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licencia: .
        /// </summary>
        internal static string Contact_LicenseLabel {
            get {
                return ResourceManager.GetString("Contact_LicenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación.
        /// </summary>
        internal static string Contact_LocationLabel {
            get {
                return ResourceManager.GetString("Contact_LocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Lo sentimos! Envío de correo fallido..
        /// </summary>
        internal static string Contact_MailErrorMessage {
            get {
                return ResourceManager.GetString("Contact_MailErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envío de correo fallido.
        /// </summary>
        internal static string Contact_MailInvalidErrorTitle {
            get {
                return ResourceManager.GetString("Contact_MailInvalidErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        internal static string Contact_MailLabel {
            get {
                return ResourceManager.GetString("Contact_MailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono oficina: .
        /// </summary>
        internal static string Contact_OficeNumberLabel {
            get {
                return ResourceManager.GetString("Contact_OficeNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        internal static string Contact_PhoneLabel {
            get {
                return ResourceManager.GetString("Contact_PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS.
        /// </summary>
        internal static string Contact_PhoneMessageLabel {
            get {
                return ResourceManager.GetString("Contact_PhoneMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono móvil: .
        /// </summary>
        internal static string Contact_PhoneNumberLabel {
            get {
                return ResourceManager.GetString("Contact_PhoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo: .
        /// </summary>
        internal static string Contact_SecondMailLabel {
            get {
                return ResourceManager.GetString("Contact_SecondMailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Lo sentimos! Envío de SMS fallido..
        /// </summary>
        internal static string Contact_SmsErrorMessage {
            get {
                return ResourceManager.GetString("Contact_SmsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Lo sentimos! SMS no compatible con el dispositivo..
        /// </summary>
        internal static string Contact_SmsSupportPhoneErrorMessage {
            get {
                return ResourceManager.GetString("Contact_SmsSupportPhoneErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envío de sms fallido.
        /// </summary>
        internal static string Contact_SmsSupportPhoneErrorTitle {
            get {
                return ResourceManager.GetString("Contact_SmsSupportPhoneErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Lo sentimos! La aplicación seleccionada no puede ser abierta o no se encuentra instalada en el dispositivo..
        /// </summary>
        internal static string Contact_SocialMediaErrorMessage {
            get {
                return ResourceManager.GetString("Contact_SocialMediaErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al abrir.
        /// </summary>
        internal static string Contact_SocialMediaErrorTitle {
            get {
                return ResourceManager.GetString("Contact_SocialMediaErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Síguenos en nuestras redes sociales.
        /// </summary>
        internal static string Contact_SocialNetworksLabel {
            get {
                return ResourceManager.GetString("Contact_SocialNetworksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        internal static string Contact_TitleLabel {
            get {
                return ResourceManager.GetString("Contact_TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona de atención: .
        /// </summary>
        internal static string Contact_ZoneLabel {
            get {
                return ResourceManager.GetString("Contact_ZoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es.
        /// </summary>
        internal static string CurrentCulture {
            get {
                return ResourceManager.GetString("CurrentCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preguntas frecuentes.
        /// </summary>
        internal static string FAQ_TitleLabel {
            get {
                return ResourceManager.GetString("FAQ_TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string FrequentQuestions_FindLabel {
            get {
                return ResourceManager.GetString("FrequentQuestions_FindLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estamos para ayudarle.
        /// </summary>
        internal static string FrequentQuestions_HelpTitleLabel {
            get {
                return ResourceManager.GetString("FrequentQuestions_HelpTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haga Click Aquí.
        /// </summary>
        internal static string FrequentQuestions_InsuranceRedirectButton {
            get {
                return ResourceManager.GetString("FrequentQuestions_InsuranceRedirectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para ver los seguros disponibles,.
        /// </summary>
        internal static string FrequentQuestions_InsuranceRedirectLabel {
            get {
                return ResourceManager.GetString("FrequentQuestions_InsuranceRedirectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su criterio de búsqueda no obtuvo resultados, pruebe nuevamente con otros criterios..
        /// </summary>
        internal static string FrequentQuestions_ListEmptyLabel {
            get {
                return ResourceManager.GetString("FrequentQuestions_ListEmptyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MÁS INFORMACIÓN.
        /// </summary>
        internal static string Home_ButtonMoreInformation {
            get {
                return ResourceManager.GetString("Home_ButtonMoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguros.
        /// </summary>
        internal static string Insurance_TitleLabel {
            get {
                return ResourceManager.GetString("Insurance_TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de seguro.
        /// </summary>
        internal static string InsuranceDetail_TitleLabel {
            get {
                return ResourceManager.GetString("InsuranceDetail_TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficios.
        /// </summary>
        internal static string InsuranceQuote_BenefitLabel {
            get {
                return ResourceManager.GetString("InsuranceQuote_BenefitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOLICITAR COTIZACIÓN.
        /// </summary>
        internal static string InsuranceQuote_ButtonLabel {
            get {
                return ResourceManager.GetString("InsuranceQuote_ButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Lo sentimos! Su solicitud no puede ser procesada en este momento..
        /// </summary>
        internal static string InsuranceQuote_ErrorMessage {
            get {
                return ResourceManager.GetString("InsuranceQuote_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string InsuranceQuote_ErrorTitle {
            get {
                return ResourceManager.GetString("InsuranceQuote_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN Corredora.
        /// </summary>
        internal static string InsuranceQuote_FooterText {
            get {
                return ResourceManager.GetString("InsuranceQuote_FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Lo sentimos! Su solicitud de cotización no puede ser procesada en este momento..
        /// </summary>
        internal static string InsuranceQuote_PopupErrorMessage {
            get {
                return ResourceManager.GetString("InsuranceQuote_PopupErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envío de correo fallido.
        /// </summary>
        internal static string InsuranceQuote_PopupErrorTitle {
            get {
                return ResourceManager.GetString("InsuranceQuote_PopupErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La información de las cotizaciones seleccionadas ha sido enviada a su correo electrónico..
        /// </summary>
        internal static string InsuranceQuote_PopupMessage {
            get {
                return ResourceManager.GetString("InsuranceQuote_PopupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud enviada.
        /// </summary>
        internal static string InsuranceQuote_PopupTitle {
            get {
                return ResourceManager.GetString("InsuranceQuote_PopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviando datos.
        /// </summary>
        internal static string InsuranceQuote_ProgressDialogSendingData {
            get {
                return ResourceManager.GetString("InsuranceQuote_ProgressDialogSendingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENVIAR COTIZACIÓN.
        /// </summary>
        internal static string InsuranceQuote_SendButtonText {
            get {
                return ResourceManager.GetString("InsuranceQuote_SendButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condiciones.
        /// </summary>
        internal static string InsuranceQuote_TermsLabel {
            get {
                return ResourceManager.GetString("InsuranceQuote_TermsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotizaciones.
        /// </summary>
        internal static string InsuranceQuote_TitleLabel {
            get {
                return ResourceManager.GetString("InsuranceQuote_TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuncios.
        /// </summary>
        internal static string Notices_TitleLabel {
            get {
                return ResourceManager.GetString("Notices_TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprar.
        /// </summary>
        internal static string OnlineInsurances_TitleLabel {
            get {
                return ResourceManager.GetString("OnlineInsurances_TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando información.
        /// </summary>
        internal static string ProgressDialogDefaultLoading {
            get {
                return ResourceManager.GetString("ProgressDialogDefaultLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COTIZAR.
        /// </summary>
        internal static string QuoteInsuranceButton {
            get {
                return ResourceManager.GetString("QuoteInsuranceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACEPTO TÉRMINOS Y CONDICIONES.
        /// </summary>
        internal static string Request_AceptTermsAndConditionsLabel {
            get {
                return ResourceManager.GetString("Request_AceptTermsAndConditionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor de la bicicleta.
        /// </summary>
        internal static string Request_BicycleValueLabel {
            get {
                return ResourceManager.GetString("Request_BicycleValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Año de la bicicleta.
        /// </summary>
        internal static string Request_BicycleYearLabel {
            get {
                return ResourceManager.GetString("Request_BicycleYearLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de nacimiento.
        /// </summary>
        internal static string Request_BirthdayLabel {
            get {
                return ResourceManager.GetString("Request_BirthdayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de nacimiento.
        /// </summary>
        internal static string Request_BirthdayPlaceholder {
            get {
                return ResourceManager.GetString("Request_BirthdayPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una opción.
        /// </summary>
        internal static string Request_DropDownMessage {
            get {
                return ResourceManager.GetString("Request_DropDownMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        internal static string Request_EmailLabel {
            get {
                return ResourceManager.GetString("Request_EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        internal static string Request_EmailPlaceholder {
            get {
                return ResourceManager.GetString("Request_EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de identificación.
        /// </summary>
        internal static string Request_IdNumberLabel {
            get {
                return ResourceManager.GetString("Request_IdNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de identificación.
        /// </summary>
        internal static string Request_IdNumberPlaceholder {
            get {
                return ResourceManager.GetString("Request_IdNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha inválida.
        /// </summary>
        internal static string Request_InvalidDateMessage {
            get {
                return ResourceManager.GetString("Request_InvalidDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato válido: 116000586109.
        /// </summary>
        internal static string Request_InvalidDimexIdDataMessage {
            get {
                return ResourceManager.GetString("Request_InvalidDimexIdDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato válido: 107430246.
        /// </summary>
        internal static string Request_InvalidNacionalIdDataMessage {
            get {
                return ResourceManager.GetString("Request_InvalidNacionalIdDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono debe contener 8 dígitos.
        /// </summary>
        internal static string Request_InvalidTelephoneDataMessage {
            get {
                return ResourceManager.GetString("Request_InvalidTelephoneDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antigüedad superior 10 años. Solicite su cotización al WhatsApp 8699-2507.
        /// </summary>
        internal static string Request_InvalidYearMessage {
            get {
                return ResourceManager.GetString("Request_InvalidYearMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato válido: usuario@ejemplo.com.
        /// </summary>
        internal static string Request_InvaliEmailDataMessage {
            get {
                return ResourceManager.GetString("Request_InvaliEmailDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos.
        /// </summary>
        internal static string Request_LastNameLabel {
            get {
                return ResourceManager.GetString("Request_LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos.
        /// </summary>
        internal static string Request_LastNamePlaceholder {
            get {
                return ResourceManager.GetString("Request_LastNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desplegar lista.
        /// </summary>
        internal static string Request_ListPlaceholder {
            get {
                return ResourceManager.GetString("Request_ListPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad de asegurados.
        /// </summary>
        internal static string Request_MapfreHowManyLabel {
            get {
                return ResourceManager.GetString("Request_MapfreHowManyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de plan de seguro.
        /// </summary>
        internal static string Request_MapfreTypeInsuranceLabel {
            get {
                return ResourceManager.GetString("Request_MapfreTypeInsuranceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string Request_NameLabel {
            get {
                return ResourceManager.GetString("Request_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string Request_NamePlaceholder {
            get {
                return ResourceManager.GetString("Request_NamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de seguro.
        /// </summary>
        internal static string Request_OthersTypeInsuranceLabel {
            get {
                return ResourceManager.GetString("Request_OthersTypeInsuranceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos personales.
        /// </summary>
        internal static string Request_PersonalDataTitle {
            get {
                return ResourceManager.GetString("Request_PersonalDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGREGAR SEGUROS DE ACCIDENTES Y ASISTENCIAS.
        /// </summary>
        internal static string Request_RequestAccidentBicycleInsuranceLabel {
            get {
                return ResourceManager.GetString("Request_RequestAccidentBicycleInsuranceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos obligatorios.
        /// </summary>
        internal static string Request_RequiredDataMessage {
            get {
                return ResourceManager.GetString("Request_RequiredDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuota del crédito.
        /// </summary>
        internal static string Request_SagicorCreditQuotaLabel {
            get {
                return ResourceManager.GetString("Request_SagicorCreditQuotaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuota del crédito.
        /// </summary>
        internal static string Request_SagicorCreditQuotaPlaceholder {
            get {
                return ResourceManager.GetString("Request_SagicorCreditQuotaPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda de crédito.
        /// </summary>
        internal static string Request_SagicorTypeCurrencyLabel {
            get {
                return ResourceManager.GetString("Request_SagicorTypeCurrencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo.
        /// </summary>
        internal static string Request_SexGenderLabel {
            get {
                return ResourceManager.GetString("Request_SexGenderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos específicos.
        /// </summary>
        internal static string Request_SpecificDataTitle {
            get {
                return ResourceManager.GetString("Request_SpecificDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        internal static string Request_TelephoneLabel {
            get {
                return ResourceManager.GetString("Request_TelephoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        internal static string Request_TelephonePlaceholder {
            get {
                return ResourceManager.GetString("Request_TelephonePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda.
        /// </summary>
        internal static string Request_TypeCurrencyLabel {
            get {
                return ResourceManager.GetString("Request_TypeCurrencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de identificación.
        /// </summary>
        internal static string Request_TypeIdLabel {
            get {
                return ResourceManager.GetString("Request_TypeIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato no válido.
        /// </summary>
        internal static string Request_ValidFormatDataMessage {
            get {
                return ResourceManager.GetString("Request_ValidFormatDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string Search_EntryPlaceholder {
            get {
                return ResourceManager.GetString("Search_EntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip de la semana.
        /// </summary>
        internal static string Tip_TitleLabel {
            get {
                return ResourceManager.GetString("Tip_TitleLabel", resourceCulture);
            }
        }
    }
}
